### ISSUE TITLE
Faces

### ISSUE THREAD

**Issue by monagai** [ataka/clmemo#3]
I changed the following code in clmemo-20160326.1623 for emacs 26.
change-log-name-face -> change-log-name
change-log-date-face -> change-log-date
change-log-email-face -> change-log-face
I use clmemo everyday. Thanks.

**Comment by ataka** [comment]
@monagai 
Thank you for your comments!

I updated clmemo.el to use `change-log-name` face instead of `change-log-name-face`.  (`change-log-date-face` -> `change-log-date`, `change-log-email-face` -> `change-log-email`)
You can get the latest clmemo-20220204.1345 from MELPA.

thanks, again.
